name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "flask-github-actions-beanstalk"
  EB_APPLICATION_NAME: "flask-github-actions-s3-beanstalk"
  EB_ENVIRONMENT_NAME: "Flask-github-actions-s3-beanstal-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches:
    - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps: 
    - name: git clone our repo
      uses: actions/checkout@v4

    - name: create ZIP deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
   
    - name: configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_ACCESS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: copy deployment package to S3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

    - name: print successful job
      run: echo "CI Pipeline part finished successfully!" 

  my_cd_part:
    needs: [my_ci_part]
    runs-on: ubuntu-latest
    steps:
    - name: configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_ACCESS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION_NAME }}

    - name: create new ElasticBeanstalk Application
      run: |
        aws elacticbeanstalk create-application-version \
        --application-name ${{ EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ DEPLOY_PACKAGE_NAME }}" \
        --version-label "Ver-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"

    - name: deploynew ElasticBeanstalk APP Version
      run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

    - name: print successful job
      run: echo "CD Pipeline part finished successfully!"
