name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "flask-github-actions-beanstalk"
  EB_APPLICATION_NAME: "flask-github-actions-s3-beanstalk"
  EB_ENVIRONMENT_NAME: "Flask-github-actions-s3-beanstal-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "eu-central-1"

on:
  push:
    branches:
    - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps: 
    - name: git clone our repo
      uses: actions/checkout@v4.1.7

    - name: create ZIP deployment package
      uses: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
   
